# Generated by Django 3.2.5 on 2023-01-29 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('seller', 'Seller'), ('buyer', 'Buyer'), ('manager', 'Manager')], max_length=10)),
                ('full_name', models.CharField(max_length=300)),
                ('phone_number', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=300)),
                ('buyer_type', models.CharField(choices=[('private', 'Private'), ('company', 'Company')], max_length=10)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
