# Generated by Django 3.2.5 on 2023-01-31 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='User',
            new_name='user',
        ),
    ]
