# Generated by Django 3.2.5 on 2023-01-31 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_product_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity_type',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('lb', 'Pound')], max_length=5),
        ),
    ]
